[[redirects]]
  from = "/api/geo"
  to = "http://ip-api.com/json/"
  force = true
[[redirects]]
  from = "/api/geo-all"
  to = "http://ip-api.com/json/?fields=status,message,continent,continentCode,country,countryCode,region,regionName,city,district,zip,lat,lon,timezone,offset,currency,isp,org,as,asname,reverse,mobile,proxy,hosting,query"
  force = true
